name: dns325-firmware-builder

on:
  push:
    tags:
      - 'Release-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install
      run: sudo apt-get update -qqy && sudo apt-get install -qqy devio git rsync

    - name: Build
      run: |
        echo "building dns325 firmware..."
        make alt-f_dns325_defconfig
        make
        mkdir output/dns325
        mv output/images/dns325/Alt-F*.* output/dns325/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.CROSS_DEPLOY_KEY }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        REPOSITORY_NAME: awanga/alt-f-next_binaries
        BRANCH: firmware/dns325 # The branch the action should deploy to.
        FOLDER: output/dns325 # The folder the action should deploy.
